# Generated by Django 2.2.5 on 2019-12-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is test description myan!'),
            preserve_default=False,
        ),
    ]
