# Generated by Django 2.2.7 on 2020-01-03 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20191212_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 8, 37, 10, 62569, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='products'),
        ),
    ]
