# Generated by Django 2.2.7 on 2020-01-03 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20200103_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('P', 'Pants'), ('J', 'Jeans'), ('Swtrs', 'Sweaters'), ('J&C', 'Jacket and Coats'), ('T&Tnks', 'T-shirt and Tanks'), ('H&SS', 'Hoodies and Sweatshirts'), ('SW', 'Sport Wear')], max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 3, 14, 18, 15, 464743, tzinfo=utc)),
        ),
    ]
