# Generated by Django 2.2.7 on 2020-01-03 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20200103_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 15, 15, 38, 775298, tzinfo=utc)),
        ),
    ]
