# Generated by Django 2.2.7 on 2020-01-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_auto_20200104_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('P', 'Pants'), ('J', 'Jeans'), ('J&C', 'Jacket and Coats'), ('T&Tnks', 'T-shirt and Tanks'), ('H&SS', 'Hoodies and Sweatshirts'), ('SW', 'Sport Wear')], max_length=10),
        ),
    ]
