# Generated by Django 2.2.7 on 2020-01-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_auto_20200105_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='apartment_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='zip',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(choices=[('E', 'eSewa'), ('K', 'Khalti'), ('C', 'Cash on Delivery')], default='C', max_length=3),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
