# Generated by Django 2.2.7 on 2020-01-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_auto_20200114_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='user',
        ),
    ]
