# Generated by Django 2.2.7 on 2020-07-06 05:38

import ckeditor_uploader.fields
from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_remove_billingaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.AddField(
            model_name='item',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
